<?php
/**
 * Created by PhpStorm.
 * User: hp
 * Date: 4/20/2018
 * Time: 8:59 AM
 */


include "Personne.php";


class Patient extends Personne
{
    public $Patient_ID;
    public $isHere;
    public $Medical_Doc_Id;

    public function __construct($FirstName, $LastName, $Gender, $CIN, $Adress, $PhoneNumber,$medicalDocId)
    {
        parent::__construct($FirstName, $LastName, $Gender, $CIN, $Adress, $PhoneNumber);
        $this->Medical_Doc_Id=$medicalDocId;
    }

    /**
     * @return mixed
     */
    public function getPatientID()
    {
        return $this->Patient_ID;
    }


    /**
     * @return mixed
     */
    public function getisHere()
    {
        return $this->isHere;
    }

    /**
     * @param mixed $isHere
     */
    public function setIsHere($isHere)
    {
        $this->isHere = $isHere;
    }

    /**
     * @return mixed
     */
    public function getMedicalDocId()
    {
        return $this->Medical_Doc_Id;
    }

    /**
     * @param mixed $Medical_Doc_Id
     */
    public function setMedicalDocId($Medical_Doc_Id)
    {
        $this->Medical_Doc_Id = $Medical_Doc_Id;
    }



    public function addToDB()
    {
        try {
            parent::addToDB(); // TODO: Change the autogenerated stub
            $bd = CnxBD::getInstance();
            $req = $bd->prepare('INSERT INTO hospital_db.patient (Patient_CIN,isHere,Medical_DOC_ID) VALUES(:Patient_CIN,:isHere,:medicalDoc)');
            $req->execute(array(
                'Patient_CIN' => $this->CIN,
                'isHere' => 1,
                'medicalDoc' => $this->Medical_Doc_Id
            ));
            $this->Patient_ID = $bd->lastInsertId();
        }catch (PDOException $e){
            echo $e->getMessage();
        }
    }
}